### ISSUE TITLE
Tests should not send requests to the live API

### ISSUE THREAD

**Issue by drixselecta** [Blasterai/codaio#13]
Hello there! Thank you for your work!
If you want, I am willing to put in a little bit of work on this issue.
I have used [HTTPretty](https://github.com/gabrielfalcao/HTTPretty) in the past, but would like to try the mocking approach with pytest-mock as explained in this article:
* Maybe we https://medium.com/@cjolowicz/hypermodern-python-2-testing-ae907a920260

What do you think?

**Comment by licht1stein** [comment]
I think it would be great, since the live API tests are the reason for them being so unreliable :)

**Comment by drixselecta** [comment]
Great, I'll give it a go then!
