### ISSUE TITLE
Move CI to Github Actions

### ISSUE THREAD

**Issue by licht1stein** [Blasterai/codaio#14]

**Comment by drixselecta** [comment]
Once we start using `nox` with #17. Solving this issue should be a piece of cake using: https://github.com/marketplace/actions/setup-nox 🎉

**Comment by licht1stein** [comment]
@drixselecta I have switched to Github Actions and added automatic deploy to PyPi on merge to master.

**Comment by licht1stein** [comment]
https://github.com/Blasterai/codaio/pull/19
