### ISSUE TITLE
Upgrade Coda API from Beta to V1 before deprecation

### ISSUE THREAD

**Issue by CptMonac** [Blasterai/codaio#21]
[Coda recently released a new stable release of the API (V1) and the old beta API will be deprecated on August 21, 2020 -](https://coda.io/api-migration-guide) 
Migration is largely straightforward (updating the default CODA_API_ENDPOINT), but there are a couple of breaking changes I've tried to outline and capture below with resolution steps:

**Breaking changes**
1. API upgraded from v1beta1 to v1:
	regex update docs links in code from v1beta1 to v1
	update default **CODA_API_ENDPOINT** to "https://coda.io/apis/v1"

2. Views have been merged with tables
	**list_views**: _/docs/{docId}/views_ -> _/docs/{docId}/tables?tableTypes=view_
	**get_view**: _/docs/{docId}/views/{viewIdOrName} -> /docs/{docId}/tables/{viewIdOrName}_

3. Sections have become pages
	**list_sections**: _/docs/{docId}/sections -> /docs/{docId}/pages_
	**get_section**: _/docs/{docId}/sections/{sectionIdOrName} -> /docs/{docId}/pages/{pageIdOrName}_

**Comment by licht1stein** [comment]
This is fixed in version 0.6.1. Thank you!
