### ISSUE TITLE
Slow updating

### ISSUE THREAD

**Issue by bluefroguk1** [Blasterai/codaio#22]
I’m finding updating rows really slow.

I run the following:

```
from codaio import Coda, Document, Cell

coda = Coda('xxxx')

doc = Document('BPaCQ9TRbH', coda=coda)

table = doc.get_table('grid-aS3YxcCqqY')

row = table['i-IQNiTjKFCt']

print('Current Row Value')

print(row['c-frM4lIItoG'])

row['c-frM4lIItoG'] = 'Change Row 2'

print('After Update Line')

print(row['c-frM4lIItoG'])
```
and get the following result, suggesting the change hasn’t happened

```
Current Row Value
Cell(column=Column 2, row=Martyn1, value=Change Row 1)
After Update Line
Cell(column=Column 2, row=Martyn1, value=Change Row 1)
But after 2-3 minutes to change is reflected on the coda document.
```

This delay is causing issues with my script (i’m trying the reference the updated value soon after it’s updated).

Is there delay due to my code, or due to the API/Coda back end?

Thanks

**Comment by drixselecta** [comment]
Hello @bluefroguk1,

Thank you for your interest.

Yes, the Coda API does not change the value of the rows immediately but returns a `202 Accepted` and puts your request into a queue. Changes are only reflected once the queue system has processed the request.

Coda has just announced [changes to the API](https://coda.io/api-migration-guide) that include a new endpoint where you can query the state of asynchronous requests: `https://coda.io/apis/v1/mutationStatus/<requestId>`

This feature, however, has not yet been implemented in this python library.

Cheers

**Comment by bluefroguk1** [comment]
Makes sense. I ended up cashing my updates locally to help with my scripts while waiting to Coda to update.

Thanks for your help

Say aweseom
