### ISSUE TITLE
Unable to insert new row

### ISSUE THREAD

**Issue by bluefroguk1** [Blasterai/codaio#23]
I'm trying to insert a new row into a table - but having issues:

I run: (I'm trying to insert a new row with the value of 'Task Name' in column c-FeZUae32Bm)
```
coda = Coda(coda_api_token)
doc = Document(coda_doc, coda=coda)
table = doc.get_table('grid-mlfmnL33vL')
name_cell_a = Cell(column='c-FeZUae32Bm', value_storage='Task Name')
value_cell_a = Cell(column='c-FeZUae32Bm', value_storage='Task Name')
table.upsert_row([name_cell_a, value_cell_a])
```
and get error:
`AttributeError: 'str' object has no attribute 'id'`

What am i missing?

Also, what's the difference between name_cell and value_cell?

Thanks

**Comment by licht1stein** [comment]
@bluefroguk1 is this still an issue?
