### ISSUE TITLE
CodaApi V1 Changes

### ISSUE THREAD

**Issue by alinscodes** [Blasterai/codaio#24]
![image](https://user-images.githubusercontent.com/47319414/93580310-8978e180-f997-11ea-9083-af6ca5df4176.png)

This works with beta version of the api which will go away.
Could you make it work with new api version 1

**Comment by bluefroguk1** [comment]
CODA_API_ENDPOINT = 'https://coda.io/apis/v1' doesn't seem to fix the problem :(

**Comment by licht1stein** [comment]
@bluefroguk1 thanks, I'll take a look

**Comment by bluefroguk1** [comment]
I *think* i've updated the code to cover the new end points as per the migration guide. (I've not used github before...so might have done something wrong, they are sitting in pull requests)

**Comment by alinscodes** [comment]
I am a user of the package right now, I don't have the code to check your changes @bluefroguk1 but it would be good if @licht1stein can have a look at those

**Comment by licht1stein** [comment]
@bluefroguk1 thanks for the effort, I'll check the PR right now.

@alinscodes thanks for mentioning me.

In any case, this project needs more contributors and maintainers, so guys please let me know if you are interested :)

**Comment by licht1stein** [comment]
PRs merged, thanks to @bluefroguk1
