### ISSUE TITLE
API V1 error on doc.list_tables()

### ISSUE THREAD

**Issue by alinscodes** [Blasterai/codaio#28]
When calling doc.list_tables() I can see the following error

`__init__() got an unexpected keyword argument 'table_type'`

**Comment by alinscodes** [comment]
See latest PR #27 for fix @licht1stein

**Comment by licht1stein** [comment]
That's great. I already fixed this while working on mocking the API responses for tests, but this quick fix is better 👍

**Comment by licht1stein** [comment]
Thanks @alinscodes

**Comment by alinscodes** [comment]
I am glad you are doing some more tests, maybe there are more issues that need fixing but I just came across this one issue.

**Comment by licht1stein** [comment]
Tests are ready, they just need to be updated to conform to v1, see here https://github.com/Blasterai/codaio/pull/29
