### ISSUE TITLE
get table function issue

### ISSUE THREAD

**Issue by kasun898** [Blasterai/codaio#76]
While using the doc.get_table(<table_id>) function, we have been getting an error stating "TypeError: __init__() got an unexpected keyword argument 'view_id'"

**Comment by felipeff** [comment]
It looks like Coda implemented a new field to the get_table API and it broke the code.
I sent a MR just adding the missing field, hopefully the project maintainers can take a look at it

**Comment by licht1stein** [comment]
Merged, thanks!

**Comment by kasun898** [comment]
Hi, still I am getting this error noh

**Comment by felipeff** [comment]
The job that deploys the package to Pypi has failed: https://github.com/Blasterai/codaio/actions/runs/8988152203 
so the code is not live yet.

**Comment by kasun898** [comment]
@licht1stein highly appreciate if you can assist with this.

**Comment by licht1stein** [comment]
@kasun898 sure, done
