### ISSUE TITLE
unexpected keyword argument 'view_id' on get_table

### ISSUE THREAD

**Issue by deivisosn** [Blasterai/codaio#78]
I get a doc, the list_tables() show me 
`[Table(name='table 1'), Table(name='table 2')]`

when I try 
`table = doc.get_table('table 1')`

I got error

`Traceback (most recent call last):
  File "C:\coda\getTabelas.py", line 17, in <module>  
table = doc.get_table('table 1')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

  `File "C:\Users\deivi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\codaio\coda.py", line 797, in get_table
    return Table.from_json(table_data, document=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

  `File "C:\Users\deivi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\codaio\coda.py", line 712, in from_json
    return cls(**js, document=document)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

`TypeError: Table.__init__() got an unexpected keyword argument 'view_id'`

**Comment by ihawn** [comment]
@deivisosn  I got the same issue. It looks like what's on pypi has some differences to what is in the git source. As a temporary solution, you can copy the contents of [coda.py](https://github.com/Blasterai/codaio/blob/master/codaio/coda.py) into your package locally in site-packages/codaio. This worked for me - just make sure you don't pip install the package again or it will overwrite this "fix" :)

Ultimately the dev will have to rebuild the package and reupload to pypi

**Comment by licht1stein** [comment]
It's on pypi now
